#!/bin/sh

Noti() {
	notify-send -a "$1" -u 'normal' "$2"
}

case $1 in
    temp)
        Noti 'Temperatures' "$(temp_nc)"
        ;;
    disk)
        #i3-msg exit
        Noti 'Disks mounted' "$(dfc -d | grep '/dev/sd[ab]')"
        ;;
    ip)
        Noti 'External IP' "$(sh ~/.config/i3/scripts/ip-external)"
        ;;
    cal)
        Noti 'Calendar' "$(cal)"
        ;;
    bat)
        Noti 'Battery' "$(sh ~/.config/i3/scripts/battery)"
        ;;
    updates)
        Noti 'Available updates' "$(yaourt -Qu)"
        ;;
    *)
        echo "Usage: $0 {temp|disk|ip|cal|bat|updates}"
        exit 2
esac
